-- Run this script in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.service_orders (
  id text primary key,
  id_programacion text not null,
  client_name text not null,
  description text not null,
  arrivalDate date not null,
  status text not null check (status in ('En camino', 'Procesando', 'En corral')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_order_animals (
  id uuid primary key default gen_random_uuid(),
  service_order_id text not null references public.service_orders (id) on delete cascade,
  quantity integer not null check (quantity > 0),
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.service_order_events (
  id bigint generated by default as identity primary key,
  service_order_id text not null references public.service_orders (id) on delete cascade,
  event_type_id integer not null,
  event_date timestamptz not null,
  description text not null,
  animals text[] not null default '{}',
  additionals jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  check (jsonb_typeof(additionals) = 'array')
);

create index if not exists service_order_animals_order_id_idx
  on public.service_order_animals (service_order_id);

create index if not exists service_order_events_order_id_idx
  on public.service_order_events (service_order_id);

create index if not exists service_order_events_date_idx
  on public.service_order_events (event_date desc);

-- Keep updated_at current whenever an order changes.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_orders_set_updated_at on public.service_orders;
create trigger service_orders_set_updated_at
before update on public.service_orders
for each row execute function public.set_updated_at();

-- Enable RLS. Add policies according to the application's authentication model
-- before exposing these tables through the Supabase client.
alter table public.service_orders enable row level security;
alter table public.service_order_animals enable row level security;
alter table public.service_order_events enable row level security;